FROM python:3.10.8-slim-buster

RUN apt-get update

RUN apt-get install curl vim -y

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY . .

RUN pip install -e /usr/src/app