version: '3.8'

services:
  chronal_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: run_chronal_api
    ports:
      - 8080:8080
    environment:
      - ALLOWED_ORIGINS=[*]
      - SECRET=secret123
      - UVICORN_RELOAD=True
      - UVICORN_WORKERS=1
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8080
      - POSTGRES_SERVER=db_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passw0rd123
      - POSTGRES_DB=chronal_db
    depends_on:
      - db_postgres
    volumes:
      - ./:/usr/src/app

  db_postgres:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_PASSWORD=passw0rd123
      - POSTGRES_USER=admin
      - POSTGRES_DB=chronal_db
    volumes:
      - chronal_api_postgres:/var/lib/postgresql

volumes:
  chronal_api_postgres:
