FROM python:3.10.8 AS development

ENV POETRY_VERSION=1.1.13
ENV POETRY_VIRTUALENVS_CREATE=false
ENV POETRY_NO_INTERACTION=1
ENV POETRY_HOME="/opt/poetry"

ENV PATH="$POETRY_HOME/bin:$PATH"

RUN pip install poetry==${POETRY_VERSION}

WORKDIR /app

COPY poetry.lock pyproject.toml ./

RUN poetry install

COPY . ./

CMD ["poetry", "run", "run_chronal_api"]