"""Add user model

Revision ID: d8cabfb28403
Revises:
Create Date: 2023-09-17 17:15:32.089128

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from chronal_api.lib.database import types

# revision identifiers, used by Alembic.
revision: str = "d8cabfb28403"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_",
        sa.Column("id", types.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("created_at", types.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", types.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("users__pkey")),
    )
    op.create_index(op.f("users__email_idx"), "users_", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("users__email_idx"), table_name="users_")
    op.drop_table("users_")
    # ### end Alembic commands ###
