"""Add calendar model

Revision ID: c478d2979abb
Revises: 04addf38ef28
Create Date: 2023-10-08 22:28:58.523643

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from chronal_api.lib.database import types

# revision identifiers, used by Alembic.
revision: str = "c478d2979abb"
down_revision: Union[str, None] = "04addf38ef28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendars",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", types.UUID(), nullable=False),
        sa.Column("id", types.UUID(), nullable=False),
        sa.Column("created_at", types.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", types.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users_.id"], name=op.f("calendars_owner_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("calendars_pkey")),
    )
    op.create_index(op.f("calendars_owner_id_idx"), "calendars", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("calendars_owner_id_idx"), table_name="calendars")
    op.drop_table("calendars")
    # ### end Alembic commands ###
