"""Add access token model

Revision ID: 04addf38ef28
Revises: d8cabfb28403
Create Date: 2023-09-19 18:19:27.500906

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from chronal_api.lib.database import types

# revision identifiers, used by Alembic.
revision: str = "04addf38ef28"
down_revision: Union[str, None] = "d8cabfb28403"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_tokens",
        sa.Column("access_token", sa.String(length=1024), nullable=False),
        sa.Column("user_id", types.UUID(), nullable=False),
        sa.Column("expiration_date", types.DateTimeUTC(), nullable=False),
        sa.Column("created_at", types.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", types.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users_.id"], name=op.f("access_tokens_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("access_token", name=op.f("access_tokens_pkey")),
    )
    op.create_index(op.f("access_tokens_user_id_idx"), "access_tokens", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("access_tokens_user_id_idx"), table_name="access_tokens")
    op.drop_table("access_tokens")
    # ### end Alembic commands ###
